title: "Dominik Speckbacher – IT Knowledge Base"
description: "Homelab • Netzwerke • Automatisierung • Forschung • Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

url: "https://specklab.github.io"
baseurl: "/workflows"

permalink: pretty

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  playbooks:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

author:
  name: "Dominik Speckbacher"
  avatar: "/assets/images/avatar.jpg"
  links:
    - label: "GitHub"
      url: "https://github.com/specklab"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/dominik-speckbacher"

header:
  sticky: true
