title: "Dominik Speckbacher – IT Knowledge Base"
description: "Homelab • Netzwerke • Automatisierung • Forschung • Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
# ➕ Eigene Includes (Mermaid & Chart.js)
includes_dir: _includes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed


plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
collections:
  projects:
    output: true
  playbooks:
    output: true
  research:
    output: true
author:
  name: "Dominik Speckbacher"
  avatar: "/assets/images/avatar.jpg"
  links:
    - label: "GitHub"
      url: "https://github.com/dominik-speckbacher"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/dominik-speckbacher"
