title: "Dominik Speckbacher – IT Knowledge Base"
description: "Homelab • Netzwerke • Automatisierung • Forschung • Portfolio"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"   # Alternativen: air, contrast, dark, neon, …

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

# Deployment
url: "https://specklab.github.io"
baseurl: "/workflows"

# Permalinks
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  playbooks:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Author Info
author:
  name: "Dominik Speckbacher"
  avatar: "/assets/images/avatar.jpg"
  links:
    - label: "GitHub"
      url: "https://github.com/specklab"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/dominik-speckbacher"

# Header
header:
  sticky: true

# SCSS
sass:
  sass_dir: _sass
  style: compressed

# Defaults für alle Seiten
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"





